DROP TABLE roles CASCADE;
DROP TABLE users CASCADE;

CREATE TABLE roles (
                       role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       role_name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO roles(role_name) VALUES ('USER');
INSERT INTO roles(role_name) VALUES ('ADMIN');

CREATE TABLE statuses (
                          status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          status_name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO statuses(status_name) VALUES ('ACTIVE');
INSERT INTO statuses(status_name) VALUES ('BANNED');

CREATE TABLE users (
                       user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       phone VARCHAR(255) NOT NULL,
                       first_name VARCHAR(255) NOT NULL,
                       second_name VARCHAR(255) NOT NULL,
                       patronymic_name VARCHAR(255),
                       role integer REFERENCES roles(role_id),
                       status VARCHAR(255) DEFAULT('ACTIVE'),
                       created_at timestamptz NOT NULL,
                       last_login timestamptz
);

/*CREATE TABLE users (
                       user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       phone VARCHAR(255) NOT NULL,
                       first_name VARCHAR(255) NOT NULL,
                       second_name VARCHAR(255) NOT NULL,
                       patronymic_name VARCHAR(255),
                       role VARCHAR(255) DEFAULT ('USER'),
                       status VARCHAR(255) DEFAULT('ACTIVE'),
                       created_at timestamptz NOT NULL,
                       last_login timestamptz
);

  DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS statuses CASCADE;

CREATE TABLE roles (
    role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO roles(role_name) VALUES ('USER');
INSERT INTO roles(role_name) VALUES ('ADMIN');

CREATE TABLE statuses (
    status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO statuses(status_name) VALUES ('ACTIVE');
INSERT INTO statuses(status_name) VALUES ('BANNED');

CREATE TABLE users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    second_name VARCHAR(255) NOT NULL,
    patronymic_name VARCHAR(255),
    role_id integer REFERENCES roles(role_id) DEFAULT (1),
    status_id integer REFERENCES statuses(status_id) DEFAULT (1),
    created_at timestamptz NOT NULL,
    last_login timestamptz
);

*/