CREATE TABLE roles (
       role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       role_name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO roles(role_name) VALUES ('USER');

CREATE TABLE users (
       user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       email VARCHAR(255) NOT NULL,
       password VARCHAR(255) NOT NULL,
       phone VARCHAR(255) NOT NULL,
       first_name VARCHAR(255) NOT NULL,
       second_name VARCHAR(255) NOT NULL,
       patronymic_name VARCHAR(255),
       role integer REFERENCES roles(role_id),
       status VARCHAR(255) DEFAULT('ACTIVE')
);